name: 'Prueba de IA - GEM Redactor Creativo'

# La palabra 'on:' no lleva espacios delante
on:
  # 'workflow_dispatch:' debe tener EXACTAMENTE DOS ESPACIOS delante
  workflow_dispatch:

jobs:
  run-gemini-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Google AI Library
        run: pip install google-generativeai

      - name: Show content of python script
        run: cat test_gem.py

      - name: Run GEM script with API Key
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python test_gem.py
